In [12]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from UnivariateFunctions import Univariate as Unv

In [13]:
dataset = pd.read_csv("sales_Price.csv")
dataset

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,Rating
0,0,221900.0,3.0,2.0,1180.0,5650,1.0,0,0,3.0,...,1180,0,1955,0,98178,47.5112,122.257,1340,5650.0,Excellent
1,1,538000.0,3.0,2.0,2570.0,7242,2.0,0,0,3.0,...,2170,400,1951,0,98125,47.7210,122.319,1690,7639.0,Excellent
2,2,180000.0,2.0,2.0,770.0,10000,1.0,0,0,3.0,...,770,0,1933,0,98028,47.7379,122.233,2720,8062.0,Good
3,3,604000.0,4.0,2.0,1960.0,5000,1.0,0,0,5.0,...,1050,910,1965,0,98136,47.5208,122.393,1360,5000.0,Excellent
4,4,510000.0,3.0,2.0,1680.0,8080,1.0,0,0,3.0,...,1680,0,1987,0,98074,47.6168,122.045,1800,7503.0,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,360000.0,3.0,2.0,1530.0,1131,3.0,0,0,3.0,...,1530,0,2009,0,98103,47.6993,122.346,1530,1509.0,Excellent
21609,21609,400000.0,4.0,2.0,2310.0,5813,2.0,0,0,3.0,...,2310,0,2014,0,98146,47.5107,122.362,1830,7200.0,Excellent
21610,21610,402101.0,2.0,2.0,1020.0,1350,2.0,0,0,3.0,...,1020,0,2009,0,98144,47.5944,122.299,1020,2007.0,Excellent
21611,21611,400000.0,3.0,2.0,1600.0,2388,2.0,0,0,3.0,...,1600,0,2004,0,98027,47.5345,122.069,1410,1287.0,Excellent
21612,21612,325000.0,2.0,2.0,1020.0,1076,2.0,0,0,3.0,...,1020,0,2008,0,98144,47.5941,122.299,1020,1357.0,Excellent

In [14]:
dataset = dataset.drop(['Unnamed: 0','zipcode','lat','long'], axis = 1)

In [15]:
dataset = pd.get_dummies(dataset, dtype=int)

In [16]:
dataset.fillna(0 , inplace = True) # replacing with NA
dataset.isnull().sum()

price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront          0
view                0
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated        0
sqft_living15       0
sqft_lot15          0
Rating_Excellent    0
Rating_Good         0
dtype: int64

In [17]:
dataset

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,Rating_Excellent,Rating_Good
0,221900.0,3.0,2.0,1180.0,5650,1.0,0,0,3.0,7.0,1180,0,1955,0,1340,5650.0,1,0
1,538000.0,3.0,2.0,2570.0,7242,2.0,0,0,3.0,7.0,2170,400,1951,0,1690,7639.0,1,0
2,180000.0,2.0,2.0,770.0,10000,1.0,0,0,3.0,6.0,770,0,1933,0,2720,8062.0,0,1
3,604000.0,4.0,2.0,1960.0,5000,1.0,0,0,5.0,7.0,1050,910,1965,0,1360,5000.0,1,0
4,510000.0,3.0,2.0,1680.0,8080,1.0,0,0,3.0,8.0,1680,0,1987,0,1800,7503.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3.0,2.0,1530.0,1131,3.0,0,0,3.0,8.0,1530,0,2009,0,1530,1509.0,1,0
21609,400000.0,4.0,2.0,2310.0,5813,2.0,0,0,3.0,8.0,2310,0,2014,0,1830,7200.0,1,0
21610,402101.0,2.0,2.0,1020.0,1350,2.0,0,0,3.0,7.0,1020,0,2009,0,1020,2007.0,1,0
21611,400000.0,3.0,2.0,1600.0,2388,2.0,0,0,3.0,8.0,1600,0,2004,0,1410,1287.0,1,0
21612,325000.0,2.0,2.0,1020.0,1076,2.0,0,0,3.0,7.0,1020,0,2008,0,1020,1357.0,1,0

In [18]:
dataset = dataset.drop(['Rating_Good'],axis = 1)

In [19]:
#changing both values to int

dataset['bathrooms'] = dataset['bathrooms'].apply(np.int64)
dataset['price'] = dataset['price'].apply(np.int64)

In [20]:
# classification is the output variable, so storing it in y, x is input

independent = dataset.iloc[:,1:].values
dependent =dataset.iloc[:,0].values

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent,dependent,test_size = 0.30, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(criterion = 'absolute_error',max_features='sqrt',n_estimators=100,random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(criterion='absolute_error', max_features='sqrt',
                      random_state=0)

In [24]:
y_pred = regressor.predict(X_test)

In [25]:
y_pred

array([ 321196.3 , 1129575.  ,  517083.56, ...,  356803.99,  295083.13,
        336554.15])

In [26]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, y_pred)
r_score

0.7338811168849313

In [27]:
import pickle 
filename = "finalized_model_RF_Price_Prediction.sav"
pickle.dump(regressor,open(filename,'wb'))